### PR TITLE
Fix KIND image loading failure with Docker Desktop containerd image store

### LINKED ISSUE #904: make deploy-wva-emulated-on-kind on macos
```console
% make deploy-wva-emulated-on-kind
>>> Deploying workload-variant-autoscaler (cluster args: -t mix -n 3 -g 2   , image: ghcr.io/llm-d/llm-d-workload-variant-autoscaler:latest)
KIND=kind KUBECTL=kubectl IMG=ghcr.io/llm-d/llm-d-workload-variant-autoscaler:latest DEPLOY_LLM_D=false ENVIRONMENT=kind-emulator CREATE_CLUSTER=false CLUSTER_GPU_TYPE=nvidia-mix CLUSTER_NODES=3 CLUSTER_GPUS=4 MULTI_MODEL_TESTING= NAMESPACE_SCOPED=false SCALER_BACKEND=prometheus-adapter   \
		deploy/install.sh
[INFO] Detected IMG environment variable: ghcr.io/llm-d/llm-d-workload-variant-autoscaler:latest
[INFO] Starting Workload-Variant-Autoscaler Deployment on kind-emulator
[INFO] ===========================================================

[INFO] Checking prerequisites...
[SUCCESS] All generic prerequisites tools met
[INFO] Setting TLS verification...
[INFO] Emulated environment detected - enabling TLS skip verification for self-signed certificates
[SUCCESS] Successfully set TLS verification to: true
[INFO] Setting WVA logging level...
[INFO] Development environment - using debug logging
[SUCCESS] WVA logging level set to: debug

[INFO] Loading environment-specific functions for kind-emulator...
[INFO] Checking prerequisites...
[SUCCESS] All generic prerequisites tools met
[INFO] Checking Kubernetes-specific prerequisites...
[INFO] Cluster creation skipped (CREATE_CLUSTER=false)
[SUCCESS] Using KIND cluster 'kind-wva-gpu-cluster'
[INFO] Loading WVA image 'ghcr.io/llm-d/llm-d-workload-variant-autoscaler:latest' into KIND cluster...
[INFO] Pulling single-platform image for KIND (platform=linux/amd64) to avoid load errors...
latest: Pulling from llm-d/llm-d-workload-variant-autoscaler
a570852fae1a: Pull complete
b4e6f1bfce0a: Pull complete
b4242723c53f: Pull complete
52630fc75a18: Pull complete
d6b1b89eccac: Pull complete
ebddc55facdc: Pull complete
2780920e5dbf: Pull complete
bdfd7f7e5bf6: Pull complete
3214acf345c0: Pull complete
7c12895b777b: Pull complete
dd64bf2dd177: Pull complete
fa8ae93e2b3a: Pull complete
c172f21841df: Pull complete
b839dfae01f6: Pull complete
0218703b6314: Download complete
Digest: sha256:5cae572f2acf18bd84c01f57956db10cb975e39452ebdfbd2ca3b98047a32fa5
Status: Downloaded newer image for ghcr.io/llm-d/llm-d-workload-variant-autoscaler:latest
ghcr.io/llm-d/llm-d-workload-variant-autoscaler:latest
[SUCCESS] Pulled image 'ghcr.io/llm-d/llm-d-workload-variant-autoscaler:latest' (platform=linux/amd64)
Image: "ghcr.io/llm-d/llm-d-workload-variant-autoscaler:latest" with ID "sha256:5cae572f2acf18bd84c01f57956db10cb975e39452ebdfbd2ca3b98047a32fa5" not yet present on node "kind-wva-gpu-cluster-control-plane", loading...
Image: "ghcr.io/llm-d/llm-d-workload-variant-autoscaler:latest" with ID "sha256:5cae572f2acf18bd84c01f57956db10cb975e39452ebdfbd2ca3b98047a32fa5" not yet present on node "kind-wva-gpu-cluster-worker", loading...
Image: "ghcr.io/llm-d/llm-d-workload-variant-autoscaler:latest" with ID "sha256:5cae572f2acf18bd84c01f57956db10cb975e39452ebdfbd2ca3b98047a32fa5" not yet present on node "kind-wva-gpu-cluster-worker2", loading...
ERROR: command "docker save -o /private/var/folders/fp/4p_qynps32sg30hs3m3bs5pc0000gn/T/images-tar2493314935/images.tar ghcr.io/llm-d/llm-d-workload-variant-autoscaler:latest" failed with error: exit status 1
Command Output: Error response from daemon: unable to create manifests file: NotFound: content digest sha256:5988b2a57fbf5f12f0294e6ce7ebc5b14424b89d6a1f6d7b8bd5849fc56339c1: not found
make: *** [deploy-wva-emulated-on-kind] Error 1
```

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed https://github.com/llm-d/llm-d-workload-variant-autoscaler/issues/904

### CODE REVIEW

File: deploy/kind-emulator/install.sh [hunk 1]
```diff
@@ -201,9 +201,74 @@ load_image() {
...
+        log_info "Pulling image on node '$node'..."
+        local pull_stderr
+        if pull_stderr="$(docker exec "$node" crictl pull "$full_image" 2>&1)"; then
+            continue
+        fi
+        log_warning "crictl pull failed on node '$node': $pull_stderr"
+
+        # crictl may not resolve short names; try with docker.io prefix, but
+        # only for unqualified image names (no registry prefix like ghcr.io/).
+        if echo "$full_image" | grep -q '/.*/' ; then
```
Comment (ev-shindin) [inline deploy/kind-emulator/install.sh]: This regex requires **at least two** `/` characters. It misses common fully-qualified images with a single slash:

- `quay.io/foo:tag` → falls through to the docker.io fallback, which tries to pull `docker.io/quay.io/foo:tag` (wrong)
- `registry.k8s.io/pause:3.9` → same problem
- `localhost:5000/wva:tag` → same problem

The standard registry-detection heuristic (used by Docker, containerd, podman) is:
> If the first `/`-separated segment contains a `.`, a `:`, or equals `localhost`, it's a registry hostname.

Note: the project's default image is multi-slash so the existing regex happens to work for the default case — but any user pointing `WVA_IMAGE_REPO` at `quay.io/myorg` or `registry.k8s.io/...` hits this bug silently.

File: deploy/kind-emulator/install.sh [hunk 2]
```diff
@@ -201,9 +201,74 @@ load_image() {
...
+            # Image is fully qualified (e.g., ghcr.io/org/repo:tag) — docker.io prefix would be wrong
+            log_warning "Failed to pull image on node '$node' (image is fully qualified, skipping docker.io fallback)"
+            failed=true
+        elif pull_stderr="$(docker exec "$node" ctr --namespace=k8s.io images pull "docker.io/$full_image" 2>&1)"; then
+            # Tag so kubelet can find it by the original name
+            docker exec "$node" ctr --namespace=k8s.io images tag "docker.io/$full_image" "$full_image" || true
+        else
+            log_warning "Failed to pull image on node '$node': $pull_stderr"
+            failed=true
```
Comment (ev-shindin) [inline deploy/kind-emulator/install.sh]: If node A succeeds but node B fails, the loop completes with `failed=true`, the user sees `exit 1` — but node A already has the image. The scheduler may place pods on node B (which lacks the image), causing `ImagePullBackOff`. Operators then have to manually clean up.

Two options:

- **Fail fast**: `exit 1` inside the loop on first failure (simplest)
- **Rollback**: on any failure, run `docker exec <successful_node> ctr --namespace=k8s.io images rm "$full_image"` to return the cluster to a consistent state

Fail-fast is probably sufficient.

File: deploy/kind-emulator/install.sh [hunk 3]
```diff
@@ -201,9 +201,74 @@ load_image() {
...
+    local load_stderr
+    if load_stderr="$(kind load docker-image "$full_image" --name "$CLUSTER_NAME" 2>&1)"; then
+        log_success "Image '$full_image' loaded into KIND cluster '$CLUSTER_NAME'"
+        return
+    fi
+
+    # Only fall back to the crictl/ctr path for the known containerd image store
+    # issue (docker save fails on multi-platform manifests, kubernetes-sigs/kind#3795).
+    # For any other error, report it and abort.
+    if ! echo "$load_stderr" | grep -qi "docker save"; then
```
Comment (ev-shindin) [inline deploy/kind-emulator/install.sh]: The fallback is gated on stderr containing the literal phrase "docker save." Different `kind` versions produce different error wording (e.g., `kind v0.22.0` vs. `v0.24.0`). A future kind release could change the message and silently break the fallback path, forcing users back to the original broken behavior.

Suggested: broaden the gate to also match `"manifest"`, `"multi-platform"`, or `"no such image"` — all indicate the same root-cause class. Or just always attempt the fallback on any `kind load` error (it's cheap and logs are clear).

File: deploy/kind-emulator/install.sh [hunk 4]
```diff
@@ -201,9 +201,74 @@ load_image() {
...
+
+        # crictl may not resolve short names; try with docker.io prefix, but
+        # only for unqualified image names (no registry prefix like ghcr.io/).
+        if echo "$full_image" | grep -q '/.*/' ; then
+            # Image is fully qualified (e.g., ghcr.io/org/repo:tag) — docker.io prefix would be wrong
+            log_warning "Failed to pull image on node '$node' (image is fully qualified, skipping docker.io fallback)"
+            failed=true
+        elif pull_stderr="$(docker exec "$node" ctr --namespace=k8s.io images pull "docker.io/$full_image" 2>&1)"; then
+            # Tag so kubelet can find it by the original name
+            docker exec "$node" ctr --namespace=k8s.io images tag "docker.io/$full_image" "$full_image" || true
```
Comment (ev-shindin) [inline deploy/kind-emulator/install.sh]: If the tag already exists (e.g., retry) `ctr` returns an error. `|| true` hides that. If tagging actually failed for another reason (typo, permissions), the kubelet won't find the image by its original name and pods will fail to start — but the script reports success.

Can you check existence first?

**Review by ev-shindin — CHANGES_REQUESTED** [review]
Great work. Can you address review comments please?

File: deploy/kind-emulator/install.sh (hunk 1 above)
Comment (gyliu513) [reply deploy/kind-emulator/install.sh]: Done

File: deploy/kind-emulator/install.sh (hunk 4 above)
Comment (gyliu513) [reply deploy/kind-emulator/install.sh]: Done

File: deploy/kind-emulator/install.sh (hunk 2 above)
Comment (gyliu513) [reply deploy/kind-emulator/install.sh]: Done

File: deploy/kind-emulator/install.sh (hunk 3 above)
Comment (gyliu513) [reply deploy/kind-emulator/install.sh]: Done

**Review by gyliu513 — COMMENTED** [review]
Thanks @ev-shindin , comments addressed

**Review by ev-shindin — APPROVED** [review]
Great work! There some low priority issues to follow-up...
